-- ENTERPRISE RETAIL DATA ENGINEERING & ANALYTICS PIPELINE

USE retail_project_db;

-- Q1: AUDITING FOR MISSING VALUES (NULL INSPECTION)

SELECT * FROM sales_data
WHERE 
    transactions_id IS NULL
    OR sale_date IS NULL
    OR sale_time IS NULL
    OR gender IS NULL
    OR age IS NULL
    OR category IS NULL
    OR quantiy IS NULL
    OR cogs IS NULL
    OR total_sale IS NULL;

-- Delet rows

DELETE FROM sales_data
WHERE
    transactions_id IS NULL
    OR sale_date IS NULL
    OR sale_time IS NULL
    OR gender IS NULL
    OR age IS NULL
    OR category IS NULL
    OR quantiy IS NULL
    OR cogs IS NULL
    OR total_sale IS NULL;

-- Describing the table
DESCRIBE sales_data;

--Update the Date Strings to MySQL Format

SET SQL_SAFE_UPDATES = 0;

UPDATE sales_data
SET sale_date = STR_TO_DATE(sale_date, '%m/%d/%Y');

SET SQL_SAFE_UPDATES = 1;

ALTER TABLE sales_data
MODIFY COLUMN sale_date DATE;


-- Q1. What is the highest (maximum) and lowest (minimum) single sale amount in our store?

SELECT 
    MAX(total_sale) AS highest_single_sale,
    MIN(total_sale) AS lowest_single_sale
FROM sales_data;

-- Q2. How many total items (quantity) were sold in the 'Electronics' category?

SELECT
    SUM(quantiy) AS total_electronics_sold
FROM sales_data
WHERE category = 'Electronics';

-- Q3. List the top 3 most expensive items based on their price per unit.

SELECT DISTINCT
    category,
    price_per_unit
FROM sales_data
ORDER BY price_per_unit DESC
LIMIT 3;

-- Q4. What is the average dollar amount spent per transaction by 'Female' customers?

SELECT 
    AVG(total_sale) AS female_avg_transaction
FROM sales_data
WHERE gender = 'Female';

-- Q5. Find all sales transactions where a customer bought exactly 4 units of any item.

SELECT * 
FROM sales_data
WHERE quantiy = 4
ORDER BY total_sale DESC;

-- Q6. Which product categories have achieved a total revenue of more than $50,000?

SELECT 
    category,
    ROUND(SUM(total_sale),2) AS total_revenue
FROM sales_data
GROUP BY category
HAVING total_revenue > 50000;

-- Q7. What is the total number of orders placed during the year 2023?

SELECT 
    COUNT(*) AS total_orders_2023
FROM sales_data
WHERE YEAR(sale_date) = 2023;

-- Q8. Find the average profit made on a single transaction across the entire store.

SELECT 
    ROUND(AVG(total_sale - cogs), 2) AS average_profit_per_transaction
FROM sales_data;

-- Q9. Group our transactions by age to see how many orders come from each individual age.

SELECT 
    age,
    transactions_id,
    COUNT(*) AS total_orders_per_age
FROM sales_data
GROUP BY age
ORDER BY total_orders_per_age DESC;


-- Q10. What is the total revenue generated by 'Clothing' sales to 'Male' customers?

SELECT
    ROUND(SUM(total_sale) , 2) AS total_clothing_revenue_male
FROM sales_data
WHERE category = 'clothing'
AND gender = 'Male';
